name: Build and upload recommended package

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout python repo
      uses: actions/checkout@v2

    - name: Install Apple certificates
      if: github.ref == 'refs/heads/main'
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - name: Run build package (recommended pkg)
      run: /usr/bin/sudo ./build_python_framework_pkgs.zsh recommended "$DEV_ID"
      env:
        DEV_ID: Developer ID Installer: Clever DevOps Co. (9GQZ7KUFR6)
      working-directory: ./python

    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: python/outputs/
